apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container1
  template:
    metadata:
      labels:
        app: container1
    spec:
      containers:
        - name: container1
          image: us-central1-docker.pkg.dev/kubernates-5409-390222/container1/container1-image:1.0
          imagePullPolicy: Always
          volumeMounts:
            - name: data-volume
              mountPath: /app/Ritva_PV_dir
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: my-pvc



